version: '3.4'

services:
  seekq.interests.api:
    image: ${DOCKER_REGISTRY-}seekqinterestsapi
    ports:
      - "32704:80"
    build:
      context: .
      dockerfile: SeekQ.Interests.Api/Dockerfile
    environment:
      ASPNETCORE_ConnectionStrings__MSSQL: "Server=seekq.mssql,1433;Database=SeekQ.Interests;User Id=sa;Password=Password123"

networks:
  default:
    external:
      name: SEEKQ_NETWORK